#! /bin/sh

if [[ -z $1 ]]; then
  echo "Missing argument" 
  exit 1
fi

FILEPATH=$WORKSPACE/$1
if [[ ! -f $FILEPATH ]]; then
  echo "$1 is not a file"
  exit 2
fi

scripts=$(dirname $0)
: ${VERSION:=$($scripts/version)}

extension=".$(echo $1 | cut -s -d . -f 2-)"

if [[ $VERSION == *-SNAPSHOT ]]; then
    finaltarget="${TARGET}Dev$extension"
else
    finaltarget="${TARGET}$extension"
fi

cp $FILEPATH $finaltarget
