#!/bin/sh

if [[ -z $DIRECTORY ]]; then
  echo "Missing DIRECTORY variable"
  exit 1
fi

if [[ ! -d $DIRECTORY ]]; then
  echo "$DIRECTORY is not a directory"
  exit 2
fi

repo=$(basename $PWD .git)
tmp_clone=/tmp/updates_$repo

echo "Creating a temporary working repository in $tmp_clone"
rm -rf $tmp_clone
git clone . $tmp_clone > /dev/null

pushd $tmp_clone > /dev/null

if [[ -f $tmp_clone/list.json ]]; then
  version=$(git rev-parse HEAD)
  echo "Updating version file with $version"
  echo $version > $DIRECTORY/version

  echo "Copying list.json"
  cp $tmp_clone/list.json $DIRECTORY
fi

for dir in packages/*/; do
  pushd $dir > /dev/null
  package_name=$(basename $dir).tar.xz
  echo "Creating $package_name"
  tar -cJf $DIRECTORY/$package_name *
  popd > /dev/null
done

popd > /dev/null

echo "Deleting temporary working tree"
rm -rf $tmp_clone

echo "Success !"
